### ISSUE TITLE
[unified_analytics] Crash on flutter master branch

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/tools#252] opened 2024-03-14 15:12 UTC
```
$ flutter --version

Unhandled exception:
type 'Null' is not a subtype of type 'int' in type cast
#0      Session._refreshSessionData.parseContents (package:unified_analytics/src/session.dart:94:43)
#1      Session._refreshSessionData (package:unified_analytics/src/session.dart:98:7)
#2      new Session (package:unified_analytics/src/session.dart:37:27)
#3      new AnalyticsImpl (package:unified_analytics/src/analytics.dart:429:23)
#4      new Analytics (package:unified_analytics/src/analytics.dart:87:12)
#5      getAnalytics (package:flutter_tools/src/reporting/unified_analytics.dart:51:10)
#6      runInContext.<anonymous closure> (package:flutter_tools/src/context_runner.dart:92:24)
#7      AppContext._generateIfNecessary.<anonymous closure> (package:flutter_tools/src/base/context.dart:107:42)
#8      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:543:23)
#9      AppContext._generateIfNecessary (package:flutter_tools/src/base/context.dart:95:20)
#10     AppContext.get (package:flutter_tools/src/base/context.dart:124:32)
#11     analytics (package:flutter_tools/src/globals.dart:98:36)
#12     _handleToolError (package:flutter_tools/runner.dart:190:13)
#13     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:142:13)
#14     _rootRunBinary (dart:async/zone.dart:1423:47)
#15     _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#16     runZonedGuarded.<anonymous closure> (dart:async/zone.dart:1798:18)
#17     _Zone._processUncaughtError (dart:async/zone.dart:1081:14)
#18     _CustomZone.handleUncaughtError (dart:async/zone.dart:1285:5)
#19     Future._propagateToListeners (dart:async/future_impl.dart:797:16)
#20     Future._completeError (dart:async/future_impl.dart:660:5)
#21     Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:746:7)
#22     _rootRun (dart:async/zone.dart:1399:13)
#23     _CustomZone.run (dart:async/zone.dart:1301:19)
#24     _CustomZone.runGuarded (dart:async/zone.dart:1209:7)
#25     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1249:23)
#26     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#27     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#28     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#29     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:185:5)
```

**Comment by eliasyishak** [comment] 2024-03-14 16:05
Hey @dcharkes, thanks for sharing! Would you mind sharing if this happens every time or flakey?

**Comment by eliasyishak** [comment] 2024-03-14 16:43
Thanks for the detailed info.. chatted a bit offline about this but to clear up the error, this is likely due to a version update in package:unified_analytics that changed the file for the session file.

```jsonc
{"session_id": 123, "last_ping": 124} // old

{"session_id": 123} // new
```

This change was made in a [previous PR aimed at reducing how many times we write to disk](https://github.com/dart-lang/tools/pull/243).

So if you end up upgrading the flutter-tool (or another client of package:unified_analytics) to a version that changes this json file to the new format.... and then later you change the flutter-tool version to an older version, you will run into this error since it will try to look up `last_ping` in the json but it will fail to find it, causing a type error

**Comment by davidmorgan** [comment] 2024-03-18 11:01
Getting this one too.

I think [this catch](https://github.com/dart-lang/tools/blob/main/pkgs/unified_analytics/lib/src/session.dart#L94)

```
      parseContents();
    } on FormatException catch (err) {
```

should be more generous: parsing can fail in other ways that `FormatException`.

Or, equivalently, make `parseContents` do a try+catch internally and rethrow anything as a `FormatException`, that's a bit nicer.

Then this will work as intended for future changes, recreating the data when the format changes :)

**Comment by mit-mit** [comment] 2024-03-18 15:05
For anyone seeing this issue, please see the note at the top of https://github.com/dart-lang/sdk/issues/55212

**Comment by christopherfujino** [comment] 2024-03-19 21:13
To summarize the state of the world:

1. The patched good version of `unified_analytics` is [v5.8.8](https://github.com/dart-lang/tools/pull/256/files)
2. the Flutter CLI tool has this version rolled at HEAD as of March 15: https://github.com/flutter/flutter/commit/8d54abfc221e947ff387814b9c91b3a152ede269
3. the Dart SDK (and thus any dart tooling maintained in dart-lang/sdk) picked up this change at HEAD as of March 18 https://github.com/dart-lang/sdk/commit/87473f8e653f948430ccaf880a4e1e4f4d6a1953
4. This Dart SDK revision rolled to flutter/engine on March 18 in https://github.com/flutter/engine/pull/51509
5. This engine revision rolled to flutter/flutter on March 18: https://github.com/flutter/flutter/commit/ca864c048ebd267243c72154d063d8dd78161a2d

Thus, at the HEAD of the master channel for the Flutter SDK, this issue should be fixed, save for any tools that are maintained outside of flutter/flutter or dart-lang/sdk.

**Comment by mit-mit** [comment] 2024-03-20 16:20
@christopherfujino with that, can we resolve this issue, or are there more changes needed?

**Comment by christopherfujino** [comment] 2024-03-20 16:58
> @christopherfujino with that, can we resolve this issue, or are there more changes needed?

Let me take a look right now, see if there are any loose ends I missed, and then I will close.

**Comment by christopherfujino** [comment] 2024-03-20 20:37
> @christopherfujino with that, can we resolve this issue, or are there more changes needed?

Yes, it looks like Flutter developers should no longer be affected by this on the master channel, and Dart developers on the dev channel.

**Closed by christopherfujino** 2024-03-20 20:37 UTC
Labels: package:unified_analytics

**Comment by christopherfujino** [comment] 2024-03-20 20:46
Also, the latest beta release of Flutter appears to predate the regression (https://github.com/flutter/flutter/blob/beta/packages/flutter_tools/pubspec.yaml#L54)
